defaults:
  - _self_
  - model: play_lmp
  - exp: antmaze_play_lmp
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

wandb:
  project: "LATENT_SKILL"

hydra:
  run:
    dir: lightning_logs/${env_name}

seed: 1

devices: [0]
num_workers: 16

env_name: ???  # specified later
train_size: 1.0
eval_last_k: 5
info: ''

