defaults:
  - _self_
  - model: trajnet
  - exp: antmaze_trl
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

wandb:
  entity: 'tunglm'
  project: "pcdt"
  group: 'EXP'
  tags: null
  offline: False

hydra:
  output_subdir: null  
  run:  
    dir: .

seed: 1
env_name: ???  # specified later

max_episode_length: 1000
devices: [0]

num_workers: 16
train_size: 0.95
eval_last_k: 5
info: ''

debug: False
